version: "3.9"
services:
    web:
        build: .
        env_file:
            - .env
        ports:
            - 8080:8080
        volumes:
            - .:/usr/src/app
        command: go run .
    db:
        image: mongo
        container_name: swe-mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=team1
            - MONGO_INITDB_ROOT_PASSWORD=swe
            - MONGO_URI=mongodb://team1:swe@db:27017/swe
    db-client:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=team1
            - ME_CONFIG_MONGODB_ADMINPASSWORD=swe
            - ME_CONFIG_MONGODB_URL=mongodb://team1:swe@db:27017/
        depends_on:
            - db
